name: "Tests"

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
 run:
   shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      # Use MSYS2's bash.exe in subsequent steps.
      - if: startsWith(matrix.os, 'windows-')
        run: echo 'C:\msys64\usr\bin' >> $GITHUB_PATH
      - run: go mod download
      - run: make fmt
      - run: make tidy
      - run: make vet
      - run: make test-generate
      - run: make test-unit
      - run: make test-system
      - run: make test-heavy
  output-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - run: make install
      - run: make output-check
